import type { ChainRecord } from './types';

/**
 * Routefold chain knowledge base.
 *
 * Every entry is a categorical assessment, reviewed by hand, with public
 * references. No exact throughput, fee or TVL figures are hardcoded — those
 * change constantly and any pinned number would be misleading. Live figures are
 * layered on at runtime from a public source and always carry provenance.
 *
 * To add a chain: append a record, keep `reviewedAt` honest, and give at least
 * one reference a reader can check. `pnpm test` asserts the shape and that every
 * slug is unique.
 */
export const CHAIN_KNOWLEDGE_BASE: ChainRecord[] = [
  {
    slug: 'ethereum',
    name: 'Ethereum',
    shortName: 'Ethereum',
    family: 'ethereum-l1',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper', 'Yul'],
    finality: 'under-a-minute',
    transactionCost: 'high',
    developerToolingMaturity: 'very-high',
    stablecoinLiquidity: 'very-high',
    defiLiquidityDepth: 'very-high',
    retailUserBase: 'high',
    institutionalPresence: 'very-high',
    suitability: {
      defi: 'very-high',
      consumer: 'low',
      gaming: 'very-low',
      institutional: 'very-high',
      tokenizedAssets: 'very-high',
      payments: 'low',
      infrastructure: 'very-high',
      social: 'low',
    },
    crossChainMaturity: 'very-high',
    operationalComplexity: 'low',
    securityModel: 'l1-consensus',
    securityNotes:
      'Largest independent validator set of any smart-contract platform and the longest audited-contract history. Settlement layer for most rollups, so its security assumptions are inherited widely.',
    geographicStrength: ['Global', 'North America', 'Europe'],
    strengths: [
      'Deepest stablecoin and DeFi liquidity of any ecosystem',
      'Most mature audit, tooling and talent market',
      'Default venue for institutional and tokenized-asset issuance',
    ],
    tradeoffs: [
      'Transaction costs make high-frequency and consumer flows uneconomic',
      'Block times are unsuitable for latency-sensitive interactions',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://ethereum.org/en/developers/docs/', 'https://l2beat.com'],
    defillamaId: 'Ethereum',
  },
  {
    slug: 'arbitrum',
    name: 'Arbitrum One',
    shortName: 'Arbitrum',
    family: 'ethereum-l2-optimistic',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper', 'Rust (Stylus)'],
    finality: 'challenge-period',
    transactionCost: 'very-low',
    developerToolingMaturity: 'very-high',
    stablecoinLiquidity: 'very-high',
    defiLiquidityDepth: 'very-high',
    retailUserBase: 'high',
    institutionalPresence: 'high',
    suitability: {
      defi: 'very-high',
      consumer: 'moderate',
      gaming: 'moderate',
      institutional: 'high',
      tokenizedAssets: 'high',
      payments: 'moderate',
      infrastructure: 'high',
      social: 'moderate',
    },
    crossChainMaturity: 'very-high',
    operationalComplexity: 'low',
    securityModel: 'l2-fraud-proof',
    securityNotes:
      'Optimistic rollup settling to Ethereum with permissionless fraud proofs. Withdrawals to L1 are subject to a challenge period unless a third-party fast-bridge is used.',
    geographicStrength: ['Global', 'North America', 'Asia'],
    strengths: [
      'Largest DeFi liquidity base outside Ethereum mainnet',
      'Byte-for-byte EVM equivalence — existing Solidity deploys unchanged',
      'Stylus allows Rust and C contracts alongside Solidity',
    ],
    tradeoffs: [
      'Native L1 withdrawals wait out a challenge period',
      'Sequencer is currently operated by a single party',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://docs.arbitrum.io', 'https://l2beat.com/scaling/projects/arbitrum'],
    defillamaId: 'Arbitrum',
  },
  {
    slug: 'base',
    name: 'Base',
    shortName: 'Base',
    family: 'ethereum-l2-optimistic',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'challenge-period',
    transactionCost: 'very-low',
    developerToolingMaturity: 'very-high',
    stablecoinLiquidity: 'very-high',
    defiLiquidityDepth: 'high',
    retailUserBase: 'very-high',
    institutionalPresence: 'high',
    suitability: {
      defi: 'high',
      consumer: 'very-high',
      gaming: 'high',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'very-high',
      infrastructure: 'high',
      social: 'very-high',
    },
    crossChainMaturity: 'high',
    operationalComplexity: 'low',
    securityModel: 'l2-fraud-proof',
    securityNotes:
      'OP Stack rollup settling to Ethereum. Operated by Coinbase; inherits the OP Stack security roadmap including fault proofs. Centralised sequencer.',
    geographicStrength: ['North America', 'Global'],
    strengths: [
      'Strongest consumer and social distribution of any EVM L2',
      'Direct on-ramp path from a large regulated exchange user base',
      'Very low fees suit high-frequency consumer interactions',
    ],
    tradeoffs: [
      'Single corporate operator concentrates governance and sequencing risk',
      'Institutional and tokenized-asset presence is thinner than Ethereum mainnet',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://docs.base.org', 'https://l2beat.com/scaling/projects/base'],
    defillamaId: 'Base',
  },
  {
    slug: 'optimism',
    name: 'OP Mainnet',
    shortName: 'Optimism',
    family: 'ethereum-l2-optimistic',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'challenge-period',
    transactionCost: 'very-low',
    developerToolingMaturity: 'very-high',
    stablecoinLiquidity: 'high',
    defiLiquidityDepth: 'high',
    retailUserBase: 'high',
    institutionalPresence: 'moderate',
    suitability: {
      defi: 'high',
      consumer: 'high',
      gaming: 'moderate',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'high',
      infrastructure: 'very-high',
      social: 'high',
    },
    crossChainMaturity: 'very-high',
    operationalComplexity: 'low',
    securityModel: 'l2-fraud-proof',
    securityNotes:
      'Reference OP Stack chain settling to Ethereum, with fault proofs deployed. The Superchain model shares a security council and upgrade path across OP Stack chains.',
    geographicStrength: ['Global', 'North America', 'Europe'],
    strengths: [
      'Superchain interoperability across a large family of OP Stack chains',
      'Well-funded retroactive public-goods funding for ecosystem projects',
      'Mature, standardised rollup tooling and documentation',
    ],
    tradeoffs: [
      'Liquidity is fragmented across the Superchain rather than concentrated',
      'Native L1 withdrawals wait out a challenge period',
    ],
    ecosystemSupport: 'very-high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://docs.optimism.io', 'https://l2beat.com/scaling/projects/op-mainnet'],
    defillamaId: 'OP Mainnet',
  },
  {
    slug: 'polygon',
    name: 'Polygon PoS',
    shortName: 'Polygon',
    family: 'ethereum-sidechain',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'seconds',
    transactionCost: 'negligible',
    developerToolingMaturity: 'very-high',
    stablecoinLiquidity: 'high',
    defiLiquidityDepth: 'moderate',
    retailUserBase: 'very-high',
    institutionalPresence: 'high',
    suitability: {
      defi: 'moderate',
      consumer: 'very-high',
      gaming: 'high',
      institutional: 'high',
      tokenizedAssets: 'high',
      payments: 'very-high',
      infrastructure: 'high',
      social: 'high',
    },
    crossChainMaturity: 'very-high',
    operationalComplexity: 'low',
    securityModel: 'sidechain-consensus',
    securityNotes:
      'Independent proof-of-stake validator set with periodic checkpoints to Ethereum. Security derives from its own stake, not from Ethereum consensus.',
    geographicStrength: ['Asia', 'India', 'Latin America', 'Global'],
    strengths: [
      'Very large retail wallet base, strongest in emerging markets',
      'Established track record with enterprise and payment integrations',
      'Fees low enough for genuinely micro-value transactions',
    ],
    tradeoffs: [
      'Does not inherit Ethereum security; validator set is its own trust assumption',
      'DeFi liquidity depth has drifted below the leading L2s',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://docs.polygon.technology'],
    defillamaId: 'Polygon',
  },
  {
    slug: 'avalanche',
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    family: 'alt-l1-evm',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'sub-second',
    transactionCost: 'low',
    developerToolingMaturity: 'high',
    stablecoinLiquidity: 'high',
    defiLiquidityDepth: 'moderate',
    retailUserBase: 'moderate',
    institutionalPresence: 'very-high',
    suitability: {
      defi: 'high',
      consumer: 'moderate',
      gaming: 'high',
      institutional: 'very-high',
      tokenizedAssets: 'very-high',
      payments: 'high',
      infrastructure: 'high',
      social: 'low',
    },
    crossChainMaturity: 'high',
    operationalComplexity: 'moderate',
    securityModel: 'independent-consensus',
    securityNotes:
      'Independent validator set with fast probabilistic finality. Subnets / L1s let an issuer run a permissioned validator set with custom compliance rules.',
    geographicStrength: ['North America', 'Europe', 'Global'],
    strengths: [
      'Strongest institutional and tokenized-asset positioning outside Ethereum',
      'Sub-second finality suits settlement and trading workloads',
      'Subnets allow a dedicated, permissioned execution environment',
    ],
    tradeoffs: [
      'Retail consumer distribution is thinner than the leading L2s',
      'Running a subnet adds meaningful validator and operational overhead',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://build.avax.network/docs'],
    defillamaId: 'Avalanche',
  },
  {
    slug: 'bnb-chain',
    name: 'BNB Smart Chain',
    shortName: 'BNB Chain',
    family: 'alt-l1-evm',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'seconds',
    transactionCost: 'very-low',
    developerToolingMaturity: 'high',
    stablecoinLiquidity: 'very-high',
    defiLiquidityDepth: 'high',
    retailUserBase: 'very-high',
    institutionalPresence: 'low',
    suitability: {
      defi: 'high',
      consumer: 'high',
      gaming: 'high',
      institutional: 'very-low',
      tokenizedAssets: 'low',
      payments: 'high',
      infrastructure: 'moderate',
      social: 'moderate',
    },
    crossChainMaturity: 'high',
    operationalComplexity: 'low',
    securityModel: 'independent-consensus',
    securityNotes:
      'Proof-of-staked-authority with a comparatively small active validator set. Concentrated governance is an explicit trust assumption.',
    geographicStrength: ['Asia', 'Southeast Asia', 'Middle East'],
    strengths: [
      'Very large retail user base, especially across Asian markets',
      'Deep stablecoin liquidity and dense DEX activity',
      'Standard EVM deployment with minimal porting effort',
    ],
    tradeoffs: [
      'Small validator set and concentrated governance',
      'Regulatory posture makes it a poor fit for institutional or RWA issuance',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.bnbchain.org'],
    defillamaId: 'BSC',
  },
  {
    slug: 'solana',
    name: 'Solana',
    shortName: 'Solana',
    family: 'alt-l1-svm',
    executionEnvironment: 'SVM',
    contractLanguages: ['Rust', 'Anchor', 'C'],
    finality: 'seconds',
    transactionCost: 'negligible',
    developerToolingMaturity: 'high',
    stablecoinLiquidity: 'very-high',
    defiLiquidityDepth: 'very-high',
    retailUserBase: 'very-high',
    institutionalPresence: 'high',
    suitability: {
      defi: 'very-high',
      consumer: 'very-high',
      gaming: 'high',
      institutional: 'moderate',
      tokenizedAssets: 'high',
      payments: 'very-high',
      infrastructure: 'high',
      social: 'very-high',
    },
    crossChainMaturity: 'high',
    operationalComplexity: 'moderate',
    securityModel: 'independent-consensus',
    securityNotes:
      'Independent validator set with a parallel execution runtime. Contracts are Rust/Anchor programs; the audit and tooling market is smaller than the EVM equivalent.',
    geographicStrength: ['North America', 'Asia', 'Global'],
    strengths: [
      'Highest consumer transaction volume of any ecosystem in this base',
      'Negligible fees with fast confirmation suit payments and high-frequency apps',
      'Very deep stablecoin liquidity and mature DEX infrastructure',
    ],
    tradeoffs: [
      'Non-EVM: Solidity contracts must be rewritten in Rust',
      'Smaller pool of auditors and engineers relative to EVM',
      'Local fee markets require deliberate transaction-priority engineering',
    ],
    ecosystemSupport: 'very-high',
    dataConfidence: 'high',
    reviewedAt: '2026-07-01',
    references: ['https://solana.com/docs', 'https://www.anchor-lang.com'],
    defillamaId: 'Solana',
  },
  {
    slug: 'sui',
    name: 'Sui',
    shortName: 'Sui',
    family: 'alt-l1-move',
    executionEnvironment: 'MoveVM',
    contractLanguages: ['Move'],
    finality: 'sub-second',
    transactionCost: 'negligible',
    developerToolingMaturity: 'moderate',
    stablecoinLiquidity: 'moderate',
    defiLiquidityDepth: 'moderate',
    retailUserBase: 'moderate',
    institutionalPresence: 'low',
    suitability: {
      defi: 'moderate',
      consumer: 'high',
      gaming: 'very-high',
      institutional: 'low',
      tokenizedAssets: 'moderate',
      payments: 'high',
      infrastructure: 'moderate',
      social: 'high',
    },
    crossChainMaturity: 'moderate',
    operationalComplexity: 'moderate',
    securityModel: 'independent-consensus',
    securityNotes:
      'Object-centric Move runtime with parallel execution. The object model prevents several classes of reentrancy bug by construction, but the auditor pool is comparatively small.',
    geographicStrength: ['Asia', 'Global'],
    strengths: [
      'Object model and sponsored transactions suit gaming and consumer UX',
      'Sub-second finality with negligible fees',
      'Move resource semantics reduce whole categories of asset-handling bugs',
    ],
    tradeoffs: [
      'Non-EVM: requires a Move rewrite and a new audit relationship',
      'Stablecoin and DeFi depth well below the leading ecosystems',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.sui.io'],
    defillamaId: 'Sui',
  },
  {
    slug: 'aptos',
    name: 'Aptos',
    shortName: 'Aptos',
    family: 'alt-l1-move',
    executionEnvironment: 'MoveVM',
    contractLanguages: ['Move'],
    finality: 'sub-second',
    transactionCost: 'negligible',
    developerToolingMaturity: 'moderate',
    stablecoinLiquidity: 'moderate',
    defiLiquidityDepth: 'low',
    retailUserBase: 'moderate',
    institutionalPresence: 'moderate',
    suitability: {
      defi: 'moderate',
      consumer: 'high',
      gaming: 'high',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'high',
      infrastructure: 'moderate',
      social: 'moderate',
    },
    crossChainMaturity: 'moderate',
    operationalComplexity: 'moderate',
    securityModel: 'independent-consensus',
    securityNotes:
      'Move-based independent L1 with parallel execution. Formal-verification tooling for Move is unusually strong; the practical auditor pool remains small.',
    geographicStrength: ['Asia', 'North America'],
    strengths: [
      'Move formal-verification tooling is a genuine asset for high-value contracts',
      'Sub-second finality and negligible fees',
      'Active institutional pilots in payments and tokenized assets',
    ],
    tradeoffs: [
      'Non-EVM: requires a Move rewrite',
      'DeFi liquidity depth is the thinnest of the major alt-L1s here',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://aptos.dev'],
    defillamaId: 'Aptos',
  },
  {
    slug: 'near',
    name: 'NEAR Protocol',
    shortName: 'NEAR',
    family: 'alt-l1-wasm',
    executionEnvironment: 'NEAR-VM',
    contractLanguages: ['Rust', 'JavaScript', 'Solidity (Aurora)'],
    finality: 'seconds',
    transactionCost: 'negligible',
    developerToolingMaturity: 'moderate',
    stablecoinLiquidity: 'low',
    defiLiquidityDepth: 'low',
    retailUserBase: 'moderate',
    institutionalPresence: 'low',
    suitability: {
      defi: 'low',
      consumer: 'very-high',
      gaming: 'moderate',
      institutional: 'low',
      tokenizedAssets: 'low',
      payments: 'high',
      infrastructure: 'high',
      social: 'high',
    },
    crossChainMaturity: 'high',
    operationalComplexity: 'moderate',
    securityModel: 'independent-consensus',
    securityNotes:
      'Sharded independent L1. Chain-signature primitives allow NEAR accounts to control addresses on other chains, which is a distinctive but relatively young mechanism.',
    geographicStrength: ['Global', 'Asia', 'Europe'],
    strengths: [
      'Named accounts and account abstraction give the best onboarding UX in this base',
      'Chain signatures enable cross-chain control without a classic bridge',
      'Aurora provides an EVM path without abandoning the NEAR account model',
    ],
    tradeoffs: [
      'Stablecoin and DeFi liquidity are materially thinner than peers',
      'Native contracts are Rust; the EVM path adds an extra layer to reason about',
    ],
    ecosystemSupport: 'high',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.near.org'],
    defillamaId: 'Near',
  },
  {
    slug: 'celestia',
    name: 'Celestia',
    shortName: 'Celestia',
    family: 'modular-da',
    executionEnvironment: 'DA-layer',
    contractLanguages: ['n/a — data availability layer'],
    finality: 'seconds',
    transactionCost: 'very-low',
    developerToolingMaturity: 'moderate',
    stablecoinLiquidity: 'very-low',
    defiLiquidityDepth: 'very-low',
    retailUserBase: 'low',
    institutionalPresence: 'low',
    suitability: {
      defi: 'very-low',
      consumer: 'very-low',
      gaming: 'low',
      institutional: 'very-low',
      tokenizedAssets: 'very-low',
      payments: 'very-low',
      infrastructure: 'very-high',
      social: 'very-low',
    },
    crossChainMaturity: 'moderate',
    operationalComplexity: 'high',
    securityModel: 'shared-security',
    securityNotes:
      'Data-availability layer, not a smart-contract platform. Applications do not deploy contracts here; rollups post data to it and keep their own execution and settlement assumptions.',
    geographicStrength: ['Global'],
    strengths: [
      'Substantially cheaper data availability than posting to Ethereum calldata',
      'Data-availability sampling lets light clients verify without full nodes',
      'The right choice when a product genuinely needs its own execution layer',
    ],
    tradeoffs: [
      'Not a deployment target for application contracts',
      'Choosing it means owning a rollup: sequencer, bridge, settlement and monitoring',
      'No native user base or liquidity to expand into',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.celestia.org'],
    defillamaId: 'Celestia',
  },
  {
    slug: 'cosmos',
    name: 'Cosmos Ecosystem',
    shortName: 'Cosmos',
    family: 'appchain-framework',
    executionEnvironment: 'CosmWasm',
    contractLanguages: ['Rust (CosmWasm)', 'Go (native modules)'],
    finality: 'seconds',
    transactionCost: 'very-low',
    developerToolingMaturity: 'moderate',
    stablecoinLiquidity: 'low',
    defiLiquidityDepth: 'low',
    retailUserBase: 'low',
    institutionalPresence: 'low',
    suitability: {
      defi: 'moderate',
      consumer: 'low',
      gaming: 'low',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'moderate',
      infrastructure: 'very-high',
      social: 'very-low',
    },
    crossChainMaturity: 'very-high',
    operationalComplexity: 'very-high',
    securityModel: 'independent-consensus',
    securityNotes:
      'A framework, not a single chain. Each appchain runs its own validator set unless it rents security through interchain security. Trust assumptions are per-chain.',
    geographicStrength: ['Global', 'Europe', 'Asia'],
    strengths: [
      'IBC is the most battle-tested trust-minimised messaging standard in production',
      'Full control of the execution layer, fee token and block-space policy',
      'Interchain security lets a new chain rent an established validator set',
    ],
    tradeoffs: [
      'Highest operational burden here — a validator set is a permanent commitment',
      'Liquidity and users must be bootstrapped from close to zero',
      'Only justified when sovereignty is a real product requirement',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.cosmos.network', 'https://ibc.cosmos.network'],
    defillamaId: 'Cosmos',
  },
  {
    slug: 'scroll',
    name: 'Scroll',
    shortName: 'Scroll',
    family: 'ethereum-l2-zk',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'minutes',
    transactionCost: 'very-low',
    developerToolingMaturity: 'high',
    stablecoinLiquidity: 'low',
    defiLiquidityDepth: 'low',
    retailUserBase: 'low',
    institutionalPresence: 'low',
    suitability: {
      defi: 'moderate',
      consumer: 'moderate',
      gaming: 'low',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'moderate',
      infrastructure: 'high',
      social: 'low',
    },
    crossChainMaturity: 'moderate',
    operationalComplexity: 'low',
    securityModel: 'l2-validity-proof',
    securityNotes:
      'Bytecode-equivalent zkEVM settling to Ethereum. Validity proofs remove the optimistic challenge window, so canonical withdrawals settle faster than an optimistic rollup.',
    geographicStrength: ['Asia', 'Global'],
    strengths: [
      'Bytecode-level EVM equivalence — existing tooling and audits carry over',
      'Validity proofs avoid the multi-day optimistic withdrawal window',
      'Low operational overhead for a team already shipping Solidity',
    ],
    tradeoffs: [
      'Liquidity and user base are materially smaller than the leading L2s',
      'Proving infrastructure is still centralised',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.scroll.io', 'https://l2beat.com/scaling/projects/scroll'],
    defillamaId: 'Scroll',
  },
  {
    slug: 'linea',
    name: 'Linea',
    shortName: 'Linea',
    family: 'ethereum-l2-zk',
    executionEnvironment: 'EVM',
    contractLanguages: ['Solidity', 'Vyper'],
    finality: 'minutes',
    transactionCost: 'very-low',
    developerToolingMaturity: 'high',
    stablecoinLiquidity: 'moderate',
    defiLiquidityDepth: 'low',
    retailUserBase: 'moderate',
    institutionalPresence: 'moderate',
    suitability: {
      defi: 'moderate',
      consumer: 'high',
      gaming: 'moderate',
      institutional: 'moderate',
      tokenizedAssets: 'moderate',
      payments: 'moderate',
      infrastructure: 'moderate',
      social: 'moderate',
    },
    crossChainMaturity: 'moderate',
    operationalComplexity: 'low',
    securityModel: 'l2-validity-proof',
    securityNotes:
      'zkEVM settling to Ethereum, developed by Consensys. Distribution benefits from tight MetaMask integration; the prover and sequencer remain operator-run.',
    geographicStrength: ['Global', 'Europe'],
    strengths: [
      'Default wallet integration gives unusually low-friction user onboarding',
      'Validity proofs with a familiar Solidity toolchain',
      'Backed by an established infrastructure vendor with enterprise reach',
    ],
    tradeoffs: [
      'DeFi liquidity is shallow relative to the leading L2s',
      'Sequencer and prover are operator-controlled',
    ],
    ecosystemSupport: 'moderate',
    dataConfidence: 'medium',
    reviewedAt: '2026-07-01',
    references: ['https://docs.linea.build', 'https://l2beat.com/scaling/projects/linea'],
    defillamaId: 'Linea',
  },
];

const BY_SLUG = new Map(CHAIN_KNOWLEDGE_BASE.map((chain) => [chain.slug, chain]));

export function getChain(slug: string): ChainRecord | undefined {
  return BY_SLUG.get(slug);
}

export function getChains(slugs: string[]): ChainRecord[] {
  return slugs.map((slug) => BY_SLUG.get(slug)).filter((chain): chain is ChainRecord => Boolean(chain));
}

export function allChainSlugs(): string[] {
  return CHAIN_KNOWLEDGE_BASE.map((chain) => chain.slug);
}

/** The date the knowledge base as a whole was last reviewed. */
export function knowledgeBaseReviewedAt(): string {
  return CHAIN_KNOWLEDGE_BASE.map((c) => c.reviewedAt).sort().at(-1) ?? '2026-07-01';
}

export const KNOWLEDGE_BASE_VERSION = '1.0.0';
